apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "wordpress.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ template "wordpress.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "wordpress.fullname" . }}
        release: {{ .Release.Name }}
    {{- if .Values.backupEnabled  }}
      annotations:
        backup.velero.io/backup-volumes: wordpress-files
    {{- end }}
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "wordpress.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        {{- with .Values.args }}
        args:
        {{- range . }}
          - {{ . | quote }}
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ default "db" .Values.wordpressDbHost }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.wordpressPassword }}
        - name: WORDPRESS_DB_USER
          value: {{ default "wordpress" .Values.wordpressUser | quote }}
        - name: WORDPRESS_DB_NAME
          value: {{ default "wordpress" .Values.wordpressDatabase | quote }}
        {{- if .Values.timezone }}
        - name: TZ
          value: {{ .Values.timezone }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: php-ini
          mountPath: /usr/local/etc/php/conf.d/wordpress.ini
          subPath: wordpress.ini
        - name: wordpress-files
          mountPath: /var/www/html
          {{- if .Values.persistence.subPath }}
          subPath: {{ .Values.persistence.subPath }}
          {{- end }}
      volumes:
      - name: php-ini
        configMap:
          name: php-ini
      - name: wordpress-files
        persistentVolumeClaim:
          claimName: wordpress-files
      